<?php
include(RESSOURCES_PATH.'classes/common.class.php');
include(RESSOURCES_PATH.'classes/songs.class.php');
include(RESSOURCES_PATH.'classes/login.class.php');
include(RESSOURCES_PATH.'classes/news.class.php');
include(RESSOURCES_PATH.'classes/shortcodes.class.php');
include(RESSOURCES_PATH.'classes/static.class.php');
include(RESSOURCES_PATH.'classes/team.class.php');
?>